
# 图像预处理配置文件
record_id : "记录的防伪标签"
# 对应第几个水泥样本
cement_sample_index : 2
# bse放大倍数
bse_zoom_times : 100
# 样品第几个SEM成像
sample_bse_index : 1
# 对应bse放大某个倍数下，第几个BSE成像图像
zoom_bse_index : 1
# ct图像采样间隔区间
sample_interval : 4
save_temp_res : False
# endregion

# region 相关路径
# ct源文件路径
ct_src_root : "D:/workspace/ml-workspace/registration/datasets"
# bse图像源文件路径
bse_src_root : "G:/BSE"
# 处理过后图像的存放路径
data_save_root : "D:/workspace/ml-workspace/registration/datasets"
# endregion

# region 裁剪图像配置
# 中心点偏移量(遮罩的)+右移动，-左移动，+下移动，-上移动
center_offset_x : -14
center_offset_y : -35
crop_radius : 580

# 矩形裁剪配置
# rect # (left, upper, right, lower)
# 这个rect实际上也就是左上角后右下角点
rect_left : 36
rect_right : 1236
scale_bar_height : 64
# roi区域的大小
rect_roi_width : 624
rect_roi_height : 512

# 裁剪时偏移量 +右移动，-左移动，-下移动，+上移动
roi_cropped_offset : [-25, -4]
# 裁剪时的增强算法配置
bse_clipLimit : 3.0
bse_tileGridSize : [8, 8]
ct_clipLimit : 4.0
ct_tileGridSize : [16, 16]
# endregion

# region 图像分割以及遮罩相关
# 最多分的类别
class_num : 4
# 左上角为(0, 0)，下面是rect(left, top, right, down)
start_left : 270
start_top : 0
cropped_width : 256
cropped_height : 256
# 按照中心裁剪，裁剪偏移量，这个是以前那个只裁剪一个正方形小区域的位置
offset_x : 80
offset_y : -100
# 遮罩来自于从哪张图像进行分割的
mask_rect_classfied_num : 3
mask_comp_classfied_num : 5
kmeans_random_status : 256
rect_gray_cls : 0
comp_gray_cls : 0
# 腐蚀扩张形态学相关操作参数
kernel_size : 3
# 去除掉一些较大的颗粒
size_threshold : 624

# ct二值化的图像灰度值
ct_gray_cls : 126
enhanced : False
# endregion

# region 不同BSE图像到ct图像时的下采样倍数
subsample_100 : 1.39139
subsample_200 : 2.782
subsample_400 : 5.59
subsample_600 : 8.45
# endregion

# region 粗匹配时得到的结果的基本参数
ground_ct_size : [1920, 1920]
origin_ct_size : [1024, 1024]
origin_matched_size : [256, 256]
# 位于BSE图像中的剪切偏移量
bse_cropped_offset : [401, 128]
# BSE图像的兴趣域尺寸
bse_roi_size : [624, 512]
# 下采样倍数
downsample_times : 1
# 搜索的区域大小
latent_slice_area : 25

matched_slice_index : 585
matched_translate : [423, 365]
matched_rotation : 244
# endregion
